name: Test cute-shaderc
on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'Name of the artifact to download'
        required: false
        type: string
        default: 'cute-shaderc'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Download cute-shaderc.exe
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}

    - name: Make executable (Unix)
      if: runner.os != 'Windows'
      run: chmod +x cute-shaderc.exe

    - name: Run cute-shaderc.exe
      run: |
        ./cute-shaderc.exe \
          -type=draw \
          -varname=fluid_sim_shd \
          -oheader=fluid_sim_shd.h \
          samples/fluid_sim_data/fluid_sim.shd
      shell: bash

    - name: Display generated header
      run: cat fluid_sim_shd.h
      shell: bash
